// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestFour {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Downloads\\tools\\chromedriver_win32\\chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void TestFour() {
        driver.get("https://dikidi.net/ru/owner/masters/?company=590235");
        driver.manage().window().setSize(new Dimension(1296, 696));
        driver.findElement(By.cssSelector(".col-xs-3 > .btn")).click();
        driver.findElement(By.name("name")).click();
        driver.findElement(By.name("name")).sendKeys("Ксения ");
        driver.findElement(By.name("surname")).click();
        driver.findElement(By.name("post")).click();
        driver.findElement(By.name("post")).click();
        driver.findElement(By.name("post")).sendKeys("косметолог");
        driver.findElement(By.cssSelector(".form-group:nth-child(5) .filter-option")).click();
        driver.findElement(By.linkText("Косметолог")).click();
        driver.findElement(By.cssSelector(".sw > .btn")).click();
        driver.findElement(By.linkText("График")).click();
        {
            WebElement element = driver.findElement(By.linkText("График"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("weekdays")).click();
        driver.findElement(By.cssSelector(".form-group > .btn-primary")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".form-group > .btn-primary"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.linkText("Онлайн-запись")).click();
        {
            WebElement element = driver.findElement(By.linkText("Онлайн-запись"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.linkText("Услуги")).click();
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.cssSelector(".cols > .btn-group .filter-option")).click();
        driver.findElement(By.cssSelector(".open .filter-option")).click();
        driver.findElement(By.cssSelector(".btns > .btn")).click();
        driver.findElement(By.cssSelector(".filled:nth-child(1) > .form-control")).sendKeys("чистка лица");
        driver.findElement(By.cssSelector(".on-append")).click();
        driver.findElement(By.linkText("Схемы ЗП")).click();
        driver.findElement(By.linkText("Доступ")).click();
        {
            WebElement element = driver.findElement(By.linkText("Доступ"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.linkText("Фото работ")).click();
        driver.findElement(By.linkText("Оповещения")).click();
        {
            WebElement element = driver.findElement(By.linkText("Оповещения"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("#tab-settings-alerts .btn")).click();
        driver.findElement(By.cssSelector(".bootbox .bootbox-close-button")).click();
        driver.findElement(By.linkText("Задать")).click();
        driver.findElement(By.cssSelector(".form-group > .btn-primary")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".form-group > .btn-primary"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".btns > .btn")).click();
        driver.findElement(By.id("weekdays")).click();
        {
            WebElement element = driver.findElement(By.id("weekdays"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".form-group > .btn-primary")).click();
        driver.findElement(By.cssSelector(".bootbox .bootbox-close-button")).click();
    }
}