// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTwo {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Downloads\\tools\\chromedriver_win32\\chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void TestTwo() {
        driver.get("https://author.today/");
        driver.manage().window().setSize(new Dimension(1296, 696));
        driver.findElement(By.linkText("Войти")).click();
        driver.findElement(By.id("Login")).click();
        driver.findElement(By.id("Login")).sendKeys("ks.v.efimova@gmail.com");
        driver.findElement(By.cssSelector("div > form:nth-child(2)")).click();
        driver.findElement(By.name("Password")).sendKeys("xefimova92");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector(".icon-bell-o")).click();
        driver.findElement(By.cssSelector(".avatar")).click();
        driver.findElement(By.cssSelector(".avatar")).click();
        driver.findElement(By.cssSelector(".avatar")).click();
        driver.findElement(By.linkText("Выйти")).click();
    }
}